#!/bin/bash

# URL del endpoint
BASE_URL="http://localhost:1234/query"

# Lista de pruebas  completas a ejecutar
PATTERNS=(

"MATCH (p32)=[ALL TRAILS ?p1 (:knows{1,5})/:knows]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{1,5})/:likes]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{1,5})/:studyAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{1,5})/:workAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{1,5})/:hasCreator]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{1,5})/:hasTag]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{1,5})/:replyOf]=>(?y) RETURN COUNT(?p1)"


"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf{0,5})/:isSubclassOf]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})/:hasInterest]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})/:isLocatedIn]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})/:knows]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})/:likes]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})/:studyAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})/:workAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{0,5})/:hasCreator]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{0,5})/:hasTag]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{0,5})/:replyOf]=>(?y) RETURN COUNT(?p1)"

"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator)/:knows{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember)/:knows{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator)/:knows{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType)/:isSubclassOf{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf)/:isSubclassOf{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows)/:knows{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes)/:replyOf{1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf)/:replyOf{1,5}]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator)/:knows{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember)/:knows{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator)/:knows{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType)/:isSubclassOf{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf)/:isSubclassOf{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows)/:knows{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes)/:replyOf{0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf)/:replyOf{0,5}]=>(?y) RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf | :replyOf{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :knows{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :knows{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :knows{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType | :isSubclassOf{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf | :isSubclassOf{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | :knows{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :replyOf{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :replyOf{1,5})]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf{1,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{1,5})]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf{0,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf{0,5})]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows{0,5})]=>(?y) RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/:hasCreator)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/:hasTag)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:likes)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:studyAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:workAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:likes)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:studyAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:workAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:likes)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:studyAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:workAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn/:isPartOf)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf/:isPartOf)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:likes)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:studyAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:workAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:hasCreator)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:hasTag)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:replyOf)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:hasCreator)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:hasTag)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:replyOf)?]=>(?y) RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasCreator|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasCreator|:hasTag))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasCreator|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasCreator|:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasTag|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasTag|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:hasTag|:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:replyOf|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/(:replyOf|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:hasInterest|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:hasInterest|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:knows|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:knows|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:knows|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:knows|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:likes|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:likes|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/(:studyAt|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:hasInterest|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:hasInterest|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:knows|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:knows|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:knows|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:knows|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:likes|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:likes|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/(:studyAt|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:hasInterest|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:hasInterest|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:knows|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:knows|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:knows|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:knows|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:likes|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:likes|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/(:studyAt|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:hasInterest|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:hasInterest|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:knows|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:knows|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:knows|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:knows|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:likes|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:likes|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/(:studyAt|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasCreator|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasCreator|:hasTag))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasCreator|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasCreator|:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasTag|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasTag|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:hasTag|:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:replyOf|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/(:replyOf|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasCreator|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasCreator|:hasTag))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasCreator|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasCreator|:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasInterest|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasTag|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasTag|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:hasTag|:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:replyOf|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/(:replyOf|:likes))]=>(?y) RETURN COUNT(?p1)"




"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/:hasCreator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/:hasTag)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn/:isPartOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf/:isPartOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:hasCreator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:hasTag)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:replyOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:hasCreator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:hasTag)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:replyOf)]=>(?y) RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf ?)/:hasTag]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf ?)/:hasCreator]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)/:hasInterest]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)/:isLocatedIn]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)/:knows]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)/:studyAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)/:workAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)/:hasInterest]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)/:isLocatedIn]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)/:knows]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)/:studyAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)/:workAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)/:hasInterest]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)/:isLocatedIn]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)/:knows]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)/:likes]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)/:studyAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)/:workAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn ?)/:isPartOf]=>(?y) RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf ?)/:isPartOf]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)/:hasInterest]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)/:isLocatedIn]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)/:knows]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)/:likes]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)/:studyAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)/:workAt]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ?)/:hasCreator]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ?)/:hasTag]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ?)/:replyOf]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ?)/:hasCreator]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ?)/:hasTag]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ?)/:replyOf]=>(?y) RETURN COUNT(?p1)"




"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember|:containerOf)=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember|:hasModerator)=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator|:containerOf)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf|:hasCreator)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:studyAt)=>(?y) RETURN COUNT(?p1)"


"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:workAt)=>(?y) RETURN COUNT(?p1)"


"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:workAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:likes)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:studyAt)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:hasInterest)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:isLocatedIn)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:knows)=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:studyAt)=>(?y) RETURN COUNT(?p1)"


"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:hasInterest)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:isLocatedIn)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:knows)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:likes)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:studyAt)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:workAt)=>(?y))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {1,5}|:hasCreator)=>(?y))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {1,5}|:hasTag)=>(?y))] RETURN COUNT(?p1)"

"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:hasInterest)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:isLocatedIn)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:knows)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:likes)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:studyAt)=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:workAt)=>(?y))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {0,5}|:hasCreator)=>(?y))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {0,5}|:hasTag)=>(?y))] RETURN COUNT(?p1)"

"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator | :replyOf{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest | :knows{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag | :replyOf{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn | :knows{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows | :knows{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes | :knows{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt | :knows{0,5})=>(?y))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt | :knows{0,5})=>(?y))] RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf ?)|(:containerOf))] RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf ?)|(:hasMember))] RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf ?)|(:hasModerator))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator ?)|(:hasCreator))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator ?)|(:hasTag))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator ?)|(:replyOf))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:hasInterest))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:knows))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:likes))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:studyAt))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:workAt))] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember ?)|(:containerOf))] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember ?)|(:hasMember))] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember ?)|(:hasModerator))] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator ?)|(:containerOf))] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator ?)|(:hasMember))] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator ?)|(:hasModerator))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag ?)|(:hasCreator))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag ?)|(:hasTag))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag ?)|(:replyOf))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:hasInterest))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:knows))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:likes))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:studyAt))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:workAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:hasInterest))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:knows))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:likes))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:studyAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:workAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:hasInterest))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:knows))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:likes))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:studyAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:workAt))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf ?)|(:hasCreator))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf ?)|(:hasTag))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf ?)|(:replyOf))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:hasInterest))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:knows))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:likes))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:studyAt))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:workAt))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:hasInterest))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:knows))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:likes))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:studyAt))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:workAt))] RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf)|(:containerOf ?))] RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf)|(:hasMember ?))] RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf)|(:hasModerator ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator)|(:hasCreator ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator)|(:hasTag ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator)|(:replyOf ?))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:hasInterest ?))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:isLocatedIn ?))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:knows ?))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:likes ?))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:studyAt ?))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:workAt ?))] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember)|(:containerOf ?))] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember)|(:hasMember ?))] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember)|(:hasModerator ?))] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator)|(:containerOf ?))] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator)|(:hasMember ?))] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator)|(:hasModerator ?))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag)|(:hasCreator ?))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag)|(:hasTag ?))] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag)|(:replyOf ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:hasInterest ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:isLocatedIn ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:knows ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:likes ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:studyAt ?))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:workAt ?))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:hasInterest ?))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:isLocatedIn ?))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:knows ?))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:likes ?))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:studyAt ?))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:workAt ?))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:hasInterest ?))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:isLocatedIn ?))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:knows ?))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:likes ?))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:studyAt ?))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:workAt ?))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf)|(:hasCreator ?))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf)|(:hasTag ?))] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf)|(:replyOf ?))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:hasInterest ?))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:isLocatedIn ?))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:knows ?))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:likes ?))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:studyAt ?))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:workAt ?))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:hasInterest ?))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:isLocatedIn ?))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:knows ?))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:likes ?))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:studyAt ?))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:workAt ?))] RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)] RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf ?)] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest ?)] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 (:hasTag ?)] RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType ?)] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn ?)] RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf ?)] RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf ?)] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ?)] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ?)] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt ?)] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt ?)] RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ??)] RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf ??)] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest ??)] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ??)] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ??)] RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 (:hasTag ??)] RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType ??)] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn ??)] RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf ??)] RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf ??)] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ??)] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ??)] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ??)] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt ??)] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt ??)] RETURN COUNT(?p1)"



"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :knows))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :likes))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :workAt))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :likes | :knows))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :knows))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :likes))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :workAt))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :knows))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :likes))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :studyAt))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :hasInterest | :knows))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :hasInterest | :workAt))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :likes | :knows))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :studyAt | :knows))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :studyAt | :likes))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :studyAt | :workAt))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :workAt | :knows))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :workAt | :likes))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :workAt | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :likes))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :workAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :hasInterest))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :likes))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :workAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :studyAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :studyAt | :likes))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :studyAt | :workAt))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :workAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :workAt | :likes))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :workAt | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :knows))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :workAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :hasInterest))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :knows))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :workAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :studyAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :studyAt | :knows))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :studyAt | :workAt))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :workAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :workAt | :knows))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :workAt | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :knows))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :likes))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :workAt))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :hasInterest))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :knows))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :likes))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :workAt))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :likes | :knows))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :workAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :workAt | :knows))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :workAt | :likes))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :knows))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :likes))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :hasInterest))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :knows))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :likes))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :studyAt))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :likes | :knows))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :studyAt | :isLocatedIn))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :studyAt | :knows))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :studyAt | :likes))] RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :isLocatedIn ){1,5}] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :knows){1,5}] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :containerOf){1,5}] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :hasModerator){1,5}] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :containerOf){1,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :hasInterest){1,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :isLocatedIn){1,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :knows){1,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :studyAt){1,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :workAt){1,5}] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :hasCreator){1,5}] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :isLocatedIn){1,5}] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :hasInterest){1,5}] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :isLocatedIn){1,5}] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :knows){1,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :hasInterest){1,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :isLocatedIn){1,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :knows){1,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :studyAt){1,5}] RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :isLocatedIn )?] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :knows)?] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :containerOf)?] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :hasModerator)?] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :containerOf)?] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :hasInterest)?] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :isLocatedIn)?] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :knows)?] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :studyAt)?] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :workAt)?] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :hasCreator)?] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :isLocatedIn)?] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :hasInterest)?] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :isLocatedIn)?] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :knows)?] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :hasInterest)?] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :isLocatedIn)?] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :knows)?] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :studyAt)?] RETURN COUNT(?p1)"

"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :isLocatedIn ){0,5}] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :knows){0,5}] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :containerOf){0,5}] RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :hasModerator){0,5}] RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :containerOf){0,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :hasInterest){0,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :isLocatedIn){0,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :knows){0,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :studyAt){0,5}] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :workAt){0,5}] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :hasCreator){0,5}] RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :isLocatedIn){0,5}] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :hasInterest){0,5}] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :isLocatedIn){0,5}] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :knows){0,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :hasInterest){0,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :isLocatedIn){0,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :knows){0,5}] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :studyAt){0,5}] RETURN COUNT(?p1)"


"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:hasInterest / :hasType ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:isLocatedIn / :isPartOf ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :hasInterest ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :knows ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :likes ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :studyAt ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :workAt ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:likes / :hasTag ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:likes / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:studyAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:workAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:hasInterest / :hasType ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:isLocatedIn / :isPartOf ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :hasInterest ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :knows ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :likes ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :studyAt ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :workAt ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:likes / :hasTag ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:likes / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:studyAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:workAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:hasInterest / :hasType ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:isLocatedIn / :isPartOf ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :hasInterest ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :knows ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :likes ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :studyAt ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :workAt ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:likes / :hasTag ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:likes / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:studyAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:workAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:hasInterest / :hasType ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:isLocatedIn / :isPartOf ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :hasInterest ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :knows ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :likes ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :studyAt ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :workAt ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:likes / :hasTag ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:likes / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:studyAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:workAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:hasInterest / :hasType ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:isLocatedIn / :isPartOf ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :hasInterest ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :knows ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :likes ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :studyAt ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :workAt ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:likes / :hasTag ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:likes / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:studyAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:workAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:hasInterest / :hasType ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:isLocatedIn / :isPartOf ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :hasInterest ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :knows ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :likes ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :studyAt ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :workAt ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:likes / :hasTag ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:likes / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:studyAt / :isLocatedIn ))] RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:workAt / :isLocatedIn ))] RETURN COUNT(?p1)"





)
#recuerda que * es {0,4} y + es {1,4}
# Ejecutar las consultas

for PATTERN in "${PATTERNS[@]}"; do
    # Ejecutar la consulta
    RESPONSE=$(curl -s -X POST "$BASE_URL" -d "$PATTERN")
    
    # Imprimir respuesta para cada consulta (opcional)
    # echo -e "Consulta ejecutada:\n$PATTERN\nRespuesta:\n$RESPONSE\n"
done

# Confirmar que todas las consultas se completaron
echo "Todas las consultas se ejecutaron correctamente."
