#!/bin/bash

# URL del endpoint
BASE_URL="http://localhost:1234/query"

# Lista de pruebas  completas a ejecutar
PATTERNS=(



"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/:hasCreator?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf/:hasTag?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:hasInterest?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:isLocatedIn?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:knows?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:studyAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator/:workAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:hasInterest?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:isLocatedIn?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:knows?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:studyAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember/:workAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:hasInterest?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:isLocatedIn?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:knows?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:likes?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:studyAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator/:workAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn/:isPartOf?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf/:isPartOf?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:hasInterest?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:isLocatedIn?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:knows?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:likes?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:studyAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows/:workAt?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:hasCreator?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:hasTag?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes/:replyOf?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:hasCreator?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:hasTag?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf/:replyOf?)]=>(?y) RETURN COUNT(?p1)"





"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember|:containerOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember|:hasModerator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator|:containerOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf|:hasCreator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt|:studyAt)]=>(?y) RETURN COUNT(?p1)"


"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest/:hasType)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn/:isPartOf)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:hasInterest)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:isLocatedIn)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:knows)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:likes)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:studyAt)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows/:workAt)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:hasTag)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes/:isLocatedIn)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt/:isLocatedIn)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt/:isLocatedIn)|:workAt)]=>(?y) RETURN COUNT(?p1)"


"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:isLocatedIn)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:knows)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:likes)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:studyAt)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest|:workAt)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:knows)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:likes)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:studyAt)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn|:workAt)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes|:knows)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:knows)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:likes)|:workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt|:workAt)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:knows)|:studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:isLocatedIn)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:knows)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt|:likes)|:studyAt)]=>(?y) RETURN COUNT(?p1)"

































































"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {1,5}|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {1,5}|:hasCreator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {1,5}|:hasTag))]=>(?y) RETURN COUNT(?p1)"

"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows {0,5}|:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {0,5}|:hasCreator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf {0,5}|:hasTag))]=>(?y) RETURN COUNT(?p1)"

"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator | :replyOf{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest | :knows{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag | :replyOf{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn | :knows{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows | :knows{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes | :knows{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt | :knows{0,5}))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt | :knows{0,5}))]=>(?y) RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf ?)|(:containerOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf ?)|(:hasMember))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf ?)|(:hasModerator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator ?)|(:hasCreator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator ?)|(:hasTag))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator ?)|(:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest ?)|(:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember ?)|(:containerOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember ?)|(:hasMember))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember ?)|(:hasModerator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator ?)|(:containerOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator ?)|(:hasMember))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator ?)|(:hasModerator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag ?)|(:hasCreator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag ?)|(:hasTag))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag ?)|(:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn ?)|(:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows ?)|(:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes ?)|(:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf ?)|(:hasCreator))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf ?)|(:hasTag))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf ?)|(:replyOf))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt ?)|(:workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt ?)|(:workAt))]=>(?y) RETURN COUNT(?p1)"


"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf)|(:containerOf ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf)|(:hasMember ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 ((:containerOf)|(:hasModerator ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator)|(:hasCreator ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator)|(:hasTag ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:hasCreator)|(:replyOf ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:hasInterest ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:isLocatedIn ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:knows ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:likes ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:studyAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 ((:hasInterest)|(:workAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember)|(:containerOf ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember)|(:hasMember ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 ((:hasMember)|(:hasModerator ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator)|(:containerOf ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator)|(:hasMember ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 ((:hasModerator)|(:hasModerator ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag)|(:hasCreator ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag)|(:hasTag ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 ((:hasTag)|(:replyOf ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:hasInterest ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:isLocatedIn ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:knows ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:likes ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:studyAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 ((:isLocatedIn)|(:workAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:hasInterest ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:isLocatedIn ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:knows ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:likes ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:studyAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 ((:knows)|(:workAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:hasInterest ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:isLocatedIn ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:knows ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:likes ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:studyAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 ((:likes)|(:workAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf)|(:hasCreator ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf)|(:hasTag ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 ((:replyOf)|(:replyOf ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:hasInterest ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:isLocatedIn ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:knows ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:likes ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:studyAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 ((:studyAt)|(:workAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:hasInterest ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:isLocatedIn ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:knows ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:likes ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:studyAt ?))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 ((:workAt)|(:workAt ?))]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 (:hasTag ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt ?)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt ?)]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f389)=[ALL TRAILS ?p1 (:hasTag ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (t6)=[ALL TRAILS ?p1 (:hasType ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (pL6)=[ALL TRAILS ?p1 (:isPartOf ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (tc7)=[ALL TRAILS ?p1 (:isSubclassOf ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt ??)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt ??)]=>(?y) RETURN COUNT(?p1)"



"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :isLocatedIn | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :likes | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :studyAt | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest |( :workAt | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :hasInterest | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :hasInterest | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :likes | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :studyAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :studyAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :studyAt | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :workAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :workAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn |( :workAt | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :hasInterest | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :isLocatedIn | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :studyAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :studyAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :studyAt | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :workAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :workAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows |( :workAt | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :hasInterest | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :isLocatedIn | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :studyAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :studyAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :studyAt | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :workAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :workAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes |( :workAt | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :hasInterest | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :isLocatedIn | :workAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :likes | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :workAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :workAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt |( :workAt | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :hasInterest | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :hasInterest))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :likes))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :isLocatedIn | :studyAt))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :likes | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :studyAt | :isLocatedIn))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :studyAt | :knows))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt |( :studyAt | :likes))]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :isLocatedIn ){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :knows){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :containerOf){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :hasModerator){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :containerOf){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :hasInterest){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :isLocatedIn){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :knows){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :studyAt){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :workAt){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :hasCreator){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :isLocatedIn){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :hasInterest){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :isLocatedIn){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :knows){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :hasInterest){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :isLocatedIn){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :knows){1,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :studyAt){1,5}]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :isLocatedIn )?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :containerOf)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :hasModerator)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :containerOf)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :studyAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :workAt)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :hasCreator)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :hasInterest)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :isLocatedIn)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :knows)?]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :studyAt)?]=>(?y) RETURN COUNT(?p1)"

"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :isLocatedIn ){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :knows){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :containerOf){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f54)=[ALL TRAILS ?p1 (:hasMember | :hasModerator){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :containerOf){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :hasInterest){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :isLocatedIn){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :knows){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :studyAt){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | :workAt){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :hasCreator){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597159)=[ALL TRAILS ?p1 (:replyOf | :isLocatedIn){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :hasInterest){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :isLocatedIn){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :knows){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :hasInterest){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :isLocatedIn){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :knows){0,5}]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :studyAt){0,5}]=>(?y) RETURN COUNT(?p1)"


"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:hasInterest / :hasType ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:isLocatedIn / :isPartOf ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :hasInterest ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :knows ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :likes ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :studyAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:knows / :workAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:likes / :hasTag ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:likes / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:studyAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | (:workAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:hasInterest / :hasType ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:isLocatedIn / :isPartOf ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :hasInterest ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :knows ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :likes ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :studyAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:knows / :workAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:likes / :hasTag ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:likes / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:studyAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | (:workAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:hasInterest / :hasType ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:isLocatedIn / :isPartOf ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :hasInterest ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :knows ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :likes ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :studyAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:knows / :workAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:likes / :hasTag ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:likes / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:studyAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | (:workAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:hasInterest / :hasType ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:isLocatedIn / :isPartOf ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :hasInterest ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :knows ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :likes ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :studyAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:knows / :workAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:likes / :hasTag ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:likes / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:studyAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p20956)=[ALL TRAILS ?p1 (:likes | (:workAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:hasInterest / :hasType ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:isLocatedIn / :isPartOf ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :hasInterest ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :knows ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :likes ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :studyAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:knows / :workAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:likes / :hasTag ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:likes / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:studyAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | (:workAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:hasInterest / :hasType ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:isLocatedIn / :isPartOf ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :hasInterest ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :knows ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :likes ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :studyAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:knows / :workAt ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:likes / :hasTag ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:likes / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:studyAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | (:workAt / :isLocatedIn ))]=>(?y) RETURN COUNT(?p1)"


"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | :studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf | :hasMember)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f60)=[ALL TRAILS ?p1 (:containerOf | :hasModerator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:hasCreator | :replyOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p56)=[ALL TRAILS ?p1 (:hasInterest | :workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (f6)=[ALL TRAILS ?p1 (:hasModerator | :hasMember)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | :hasCreator)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | :replyOf)]=>(?y) RETURN COUNT(?p1)"
"MATCH (m2597148)=[ALL TRAILS ?p1 (:isLocatedIn | :workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | :hasInterest)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | :likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | :studyAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p32)=[ALL TRAILS ?p1 (:knows | :workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :likes)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p8)=[ALL TRAILS ?p1 (:studyAt | :workAt)]=>(?y) RETURN COUNT(?p1)"
"MATCH (p9)=[ALL TRAILS ?p1 (:workAt | :likes)]=>(?y) RETURN COUNT(?p1)"



)
#recuerda que * es {0,4} y + es {1,4}
# Ejecutar las consultas

for PATTERN in "${PATTERNS[@]}"; do
    # Ejecutar la consulta
    RESPONSE=$(curl -s -X POST "$BASE_URL" -d "$PATTERN")
    
    # Imprimir respuesta para cada consulta (opcional)
    # echo -e "Consulta ejecutada:\n$PATTERN\nRespuesta:\n$RESPONSE\n"
done

# Confirmar que todas las consultas se completaron
echo "Todas las consultas se ejecutaron correctamente."
